using UnityEngine;
using System.Collections;

public class MarbleArrowModel : MonoBehaviour {

	public GameObject arrow;

	// Use this for initialization
	void Start () {

		// set the position of the arrow
		//arrow.transform.position = new Vector3 (-1.5f, -3.1f, 0f);

		// set the rotation of the arrow (the larger the z-value, the more rotation to the left)
		//arrow.transform.rotation = Quaternion.Euler (arrow.transform.rotation.x, arrow.transform.rotation.y, 0f);
	}
	
	// Update is called once per frame
	void Update () {
	
	}

	public void HandlePressedStart () 
	{
		StartCoroutine (destroyArrow ());
	}

	public IEnumerator destroyArrow() 
	{
		yield return new WaitForSeconds(0.2f);
		Destroy(arrow);
	}
}
